<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    //guarded ou fillable para controlar adicionar posts
    //protected $guarded = ['id'];
    protected $guarded = [];//melhor opção, array vazio, id é AUTO_INCREMENT
    //protected  $fillable =

    protected $with = ['category', 'author'];

///////////////////////////////////////////////////////////////////
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    //hasOne, hasMany, belongsTo, belongsToMany
///////////////////////////////////////////////////////////////////
    public function category()
    {

        return $this->belongsTo(Category::class);
    }
////////////////////////////////////////////////////////////////////
    public function author() //laravel assume foreignKey author_id
    {
        return $this->belongsTo(User::class,'user_id');
    }


}
